# Generated by Django 3.2.13 on 2022-04-25 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longshorturl',
            name='short',
            field=models.CharField(blank=True, error_messages={'max_length': 'Максимальная длина короткой ссылки 16 символов', 'unique': 'Такая короткая ссылка уже существует'}, help_text='Опционально', max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$', 'Короткая ссылка должна содержать только буквы латинского алфавита и/или цифры')], verbose_name='Сокращенная ссылка'),
        ),
    ]
